apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend
resources:
  - ../../base
images:
  - name: gitops-backend
    newName: docker.io/simonangelfong/gitops-backend
    newTag: v0.3.0
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/instance: gitops-backend-dev
      env: dev
patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: gitops-backend
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 4
      - op: replace
        path: /spec/maxReplicas
        value: 8
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 60
