apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend
resources:
  - ../../base

images:
  - name: gitops-backend
    newName: docker.io/simonangelfong/gitops-backend
    newTag: app-v0.2.0

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/instance: gitops-backend-prod
      env: prod

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: gitops-backend
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 10
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 60
