apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-memory-health
spec:
  args:
    - name: canary-hash
  metrics:
    - name: pod-restart-count
      interval: 60s
      count: 5
      successCondition: result[0] == 0
      failureLimit: 1
      provider:
        prometheus:
          address: http://kps-prometheus.monitoring.svc.cluster.local:9090
          # how many container restart in 2 min, in backend ns.
          query: |
            sum(increase(
              kube_pod_container_status_restarts_total{
                namespace="backend",
                pod=~"gitops-backend-{{args.canary-hash}}-.*"
              }[2m]
            ))
