apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
resources:
  - ../../base
images:
  - name: gitops-risk-control-frontend
    newName: docker.io/simonangelfong/gitops-risk-control-frontend
    newTag: v0.3.3
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/instance: gitops-frontend
      env: dev
patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: gitops-frontend
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 4
      - op: replace
        path: /spec/maxReplicas
        value: 8
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 60
