apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
resources:
  - ../../base
images:
  - name: gitops-demo-frontend
    newName: docker.io/simonangelfong/gitops-demo-frontend
    newTag: v0.3.0
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/instance: gitops-demo-frontend-dev
      env: dev
patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: gitops-demo-frontend
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 80
